/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteRouteImport } from './routes/_home/route'
import { Route as HomeIndexRouteImport } from './routes/_home/index'
import { Route as HomeSettingsRouteImport } from './routes/_home/settings'
import { Route as HomeHistoryRouteImport } from './routes/_home/history'
import { Route as HomeDashboardRouteImport } from './routes/_home/dashboard'
import { Route as HomeActivitylogRouteImport } from './routes/_home/activitylog'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRouteRoute = HomeRouteRouteImport.update({
  id: '/_home',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeSettingsRoute = HomeSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeHistoryRoute = HomeHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeDashboardRoute = HomeDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeActivitylogRoute = HomeActivitylogRouteImport.update({
  id: '/activitylog',
  path: '/activitylog',
  getParentRoute: () => HomeRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof HomeIndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/activitylog': typeof HomeActivitylogRoute
  '/dashboard': typeof HomeDashboardRoute
  '/history': typeof HomeHistoryRoute
  '/settings': typeof HomeSettingsRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/activitylog': typeof HomeActivitylogRoute
  '/dashboard': typeof HomeDashboardRoute
  '/history': typeof HomeHistoryRoute
  '/settings': typeof HomeSettingsRoute
  '/': typeof HomeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_home': typeof HomeRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_home/activitylog': typeof HomeActivitylogRoute
  '/_home/dashboard': typeof HomeDashboardRoute
  '/_home/history': typeof HomeHistoryRoute
  '/_home/settings': typeof HomeSettingsRoute
  '/_home/': typeof HomeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/activitylog'
    | '/dashboard'
    | '/history'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/signup'
    | '/activitylog'
    | '/dashboard'
    | '/history'
    | '/settings'
    | '/'
  id:
    | '__root__'
    | '/_home'
    | '/login'
    | '/signup'
    | '/_home/activitylog'
    | '/_home/dashboard'
    | '/_home/history'
    | '/_home/settings'
    | '/_home/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  HomeRouteRoute: typeof HomeRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_home': {
      id: '/_home'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof HomeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_home/': {
      id: '/_home/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/_home/settings': {
      id: '/_home/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof HomeSettingsRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/_home/history': {
      id: '/_home/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HomeHistoryRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/_home/dashboard': {
      id: '/_home/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof HomeDashboardRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/_home/activitylog': {
      id: '/_home/activitylog'
      path: '/activitylog'
      fullPath: '/activitylog'
      preLoaderRoute: typeof HomeActivitylogRouteImport
      parentRoute: typeof HomeRouteRoute
    }
  }
}

interface HomeRouteRouteChildren {
  HomeActivitylogRoute: typeof HomeActivitylogRoute
  HomeDashboardRoute: typeof HomeDashboardRoute
  HomeHistoryRoute: typeof HomeHistoryRoute
  HomeSettingsRoute: typeof HomeSettingsRoute
  HomeIndexRoute: typeof HomeIndexRoute
}

const HomeRouteRouteChildren: HomeRouteRouteChildren = {
  HomeActivitylogRoute: HomeActivitylogRoute,
  HomeDashboardRoute: HomeDashboardRoute,
  HomeHistoryRoute: HomeHistoryRoute,
  HomeSettingsRoute: HomeSettingsRoute,
  HomeIndexRoute: HomeIndexRoute,
}

const HomeRouteRouteWithChildren = HomeRouteRoute._addFileChildren(
  HomeRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  HomeRouteRoute: HomeRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
